### PR TITLE
More archs simple

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pkgw** [comment]
Note that this package is one of the ones that's superseded by the `xorg-xorgproto` mega-package that upstream has migrated to, so there may not be much value to migrating it. The same goes for all of the other `*proto` packages except for `xcb-proto`.

**Comment by hmaarrfk** [comment]
> Note that this package is one of the ones that's superseded by the xorg-xorgproto mega-package that upstream has migrated to, so there may not be much value to migrating it. The same goes for all of the other *proto packages except for xcb-proto.

I guess we've never really ripped off the bandaid, so it still feels useful to maintain them.

**Comment by ehfd** [comment]
Because the megapackage still needs to be migrated starting from libx11, short-term there still needs to be the migration, especially to add architectures for new X.Org libraries depending on them. @pkgw

**Comment by pkgw** [comment]
This looks OK, but we should hold off on merging because the X.org download site seems to be having problems right now, so builds are failing due to connection errors.

**Pull request merged**
